#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from slipstream.util import nostdouterr
from slipstream.ConfigHolder import ConfigHolder
from slipstream.cloudconnectors.cloudstack.CloudStackCommand import CloudStackCommand
from slipstream.cloudconnectors.cloudstack.CloudStackClientCloud import CloudStackClientCloud


class MainProgram(CloudStackCommand):

    STATE_MAP = {0: 'Running',
                 1: 'Rebooting',
                 2: 'Terminated',
                 3: 'Pending',
                 4: 'Unknown'}

    def __init__(self):
        super(MainProgram, self).__init__()

    def doWork(self):
        with nostdouterr():
            nodes = self._list_instances()
        self._printResults(nodes)

    def _list_instances(self):
        cc = CloudStackClientCloud(ConfigHolder(options={'verboseLevel': 0},
                                                context={'foo': 'bar'}))
        cc._initialization(self.userInfo)
        return cc.list_instances()

    def _printResults(self, nodes):
        print "id state"
        for node in nodes:
            print node.id, self.STATE_MAP[node.state]


if __name__ == "__main__":
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
    except Exception as e:
        print e
        exit(1)
