#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from slipstream.command.CloudClientCommand import main
from slipstream.command.DescribeInstancesCommand import DescribeInstancesCommand
from slipstream.cloudconnectors.cloudstack.CloudStackCommand import CloudStackCommand
from slipstream.cloudconnectors.cloudstack.CloudStackClientCloud import CloudStackClientCloud


class CloudStackDescribeInstances(DescribeInstancesCommand, CloudStackCommand):

    STATE_MAP = {0: 'Running',
                 1: 'Rebooting',
                 2: 'Terminated',
                 3: 'Pending',
                 4: 'Unknown'}

    def _vm_get_state(self, cc, vm):
        return self.STATE_MAP[vm.state]

    def _vm_get_id(self, cc, vm):
        return vm.id

    def __init__(self):
        super(CloudStackDescribeInstances, self).__init__()


if __name__ == "__main__":
    main(CloudStackDescribeInstances)

