#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from slipstream.command.CloudClientCommand import main
from slipstream.command.RunInstancesCommand import RunInstancesCommand
from slipstream.cloudconnectors.openstack.OpenStackCommand import OpenStackCommand
from slipstream.cloudconnectors.openstack.OpenStackClientCloud import OpenStackClientCloud


class OpenStackRunInstances(RunInstancesCommand, OpenStackCommand):

    INSTANCE_TYPE_KEY = 'instance-type'
    SECURITY_GROUPS_KEY = 'security-groups'

    def __init__(self):
        super(OpenStackRunInstances, self).__init__()

    def set_cloud_specific_options(self, parser):
        OpenStackCommand.set_cloud_specific_options(self, parser)

        self.parser.add_option('--' + self.INSTANCE_TYPE_KEY, dest=self.INSTANCE_TYPE_KEY,
                               help='Instance Type (Flavor)',
                               default=None, metavar='TYPE')

        self.parser.add_option('--' + self.SECURITY_GROUPS_KEY, dest=self.SECURITY_GROUPS_KEY,
                               help='Comma separated list of security groups',
                               default='', metavar='SECGROUPS')

    def get_cloud_specific_node_inst_cloud_params(self):
        return {'security.groups': self.get_option(self.SECURITY_GROUPS_KEY),
                'instance.type': self.get_option(self.INSTANCE_TYPE_KEY)}

    def get_cloud_specific_mandatory_options(self):
        return OpenStackCommand.get_cloud_specific_mandatory_options(self) + \
               [self.INSTANCE_TYPE_KEY,
                self.SECURITY_GROUPS_KEY]


if __name__ == "__main__":
    main(OpenStackRunInstances)
