#!/usr/bin/env python

import sys

from slipstream.util import nostdout
from slipstream.ConfigHolder import ConfigHolder
from slipstream.cloudconnectors.openstack.OpenStackCommand import OpenStackCommand
from slipstream.cloudconnectors.openstack.OpenStackClientCloud import OpenStackClientCloud

class MainProgram(OpenStackCommand):
    def __init__(self):
        super(MainProgram, self).__init__()

    def setProgramOptions(self):
        self.parser.add_option('--instance-id', dest='instance_id',
                               help='Instance ID',
                               default='', metavar='ID')

    def checkOptions(self):
        if not self.options.instance_id:
            self.parser.error('Some options were not given values. ' + \
                              'All options are mandatory.')

    def doWork(self):
        self._stop_instance(self.options.instance_id)

    def _stop_instance(self, node_id):
        cc = OpenStackClientCloud(ConfigHolder(options={'verboseLevel':0},
                                               context={'foo':'bar'}))
        with nostdout():
            cc._initialization(self.userInfo)
        try:
            cc._stop_vms_by_ids([node_id])
        except Exception as ex:
            print ex

if __name__ == "__main__":
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
