#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)
import sys

from slipstream.util import nostdout
from slipstream.ConfigHolder import ConfigHolder
from slipstream.cloudconnectors.openstack.OpenStackCommand import OpenStackCommand
from slipstream.cloudconnectors.openstack.OpenStackClientCloud import OpenStackClientCloud



class MainProgram(OpenStackCommand):

    STATE_MAP = {0: 'Running',
                 1: 'Rebooting',
                 2: 'Terminated',
                 3: 'Pending',
                 4: 'Unknown',
                 5: 'Stopped'}

    def __init__(self):
        super(MainProgram, self).__init__()

    def doWork(self):
        with nostdout():
            nodes = self.list_instances()
        self._printResults(nodes)

    def list_instances(self):
        cc = OpenStackClientCloud(ConfigHolder(options={'verboseLevel':0},
                                               context={'foo':'bar'}))
        cc._initialization(self.userInfo)
        return cc.list_instances()

    def _printResults(self, nodes):
        print "id state"
        for node in nodes:
            print node.id, self.STATE_MAP[node.state]


if __name__ == "__main__":
    try:
        MainProgram()
    except KeyboardInterrupt:
        print '\n\nExecution interrupted by the user... goodbye!'
