#!/usr/bin/env python

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

from slipstream.command.CloudClientCommand import main
from slipstream.command.DescribeInstancesCommand import DescribeInstancesCommand
from slipstream.cloudconnectors.openstack.OpenStackCommand import OpenStackCommand
from slipstream.cloudconnectors.openstack.OpenStackClientCloud import OpenStackClientCloud


class OpenStackDescribeInstances(DescribeInstancesCommand, OpenStackCommand):

    STATE_MAP = {0: 'Running',
                 1: 'Rebooting',
                 2: 'Terminated',
                 3: 'Pending',
                 4: 'Unknown',
                 5: 'Stopped'}

    def _vm_get_state(self, cc, vm):
        return self.STATE_MAP[vm.state]

    def _vm_get_id(self, cc, vm):
        return vm.id

    def __init__(self):
        super(OpenStackDescribeInstances, self).__init__()


if __name__ == "__main__":
    main(OpenStackDescribeInstances)
