#!/usr/bin/env python

from slipstream.command.CloudClientCommand import main
from slipstream.command.TerminateInstancesCommand import TerminateInstancesCommand
from slipstream.cloudconnectors.openstack.OpenStackCommand import OpenStackCommand
from slipstream.cloudconnectors.openstack.OpenStackClientCloud import OpenStackClientCloud


class OpenStackTerminateInstances(TerminateInstancesCommand, OpenStackCommand):

    def __init__(self):
        super(OpenStackTerminateInstances, self).__init__()


if __name__ == "__main__":
    main(OpenStackTerminateInstances)

