#!/bin/bash
#
#   /etc/rc.d/init.d/slipstream-orchestrator
#
#   Start up the Slipstream Orchestrator Executor daemon.
#
# chkconfig: 2345 20 80
# description: Slipstream Orchestrator Executor daemon.
#
# processname: slipstream-orchestrator
# config: /etc/default/slipstream-orchestrator
# pidfile: /var/run/slipstream-orchestrator.pid

### BEGIN INIT INFO
# Provides: slipstream-orchestrator
# Required-Start: $network $local_fs
# Required-Stop: $network $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: S 0 1 6
# Short-Description: Start up the Slipstream Orchestrator Executor daemon
# Description:       Slipstream Orchestrator Executor daemon enables user
#                    application depoyment orchestration.
### END INIT INFO

# source function library
. /lib/lsb/init-functions

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME="slipstream-orchestrator"
LOCK_FILE=/var/lock/$NAME
RETVAL=0
if [ -z "$UID" ]; then
    UID=$(id -u)
fi

# default settings
DAEMON=/opt/slipstream/client/sbin/slipstream-orchestrator

if [ -f /etc/default/slipstream-orchestrator ]; then
  . /etc/default/slipstream-orchestrator
fi

DAEMON_ARGS="$DAEMON_ARGS"

start() {
    [ -x $DAEMON ] || exit 5
    [ $UID -ne 0 ] && exit 4
    echo -n "Starting ${NAME}: "
    $DAEMON $DAEMON_ARGS start && log_success_msg || log_failure_msg
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    echo
    return $RETVAL
}

stop() {
    [ $UID -ne 0 ] && exit 4
    echo -n "Shutting down ${NAME}: "
    $DAEMON stop && log_success_msg || log_failure_msg
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
    echo
    return $RETVAL
}

status() {
    [ $UID -ne 0 ] && exit 4
    $DAEMON status
    RETVAL=$?
    return $RETVAL
}

restart() {
    [ -x $DAEMON ] || exit 5
    [ $UID -ne 0 ] && exit 4
    echo -n "Re-starting ${NAME}: "
    $DAEMON $DAEMON_ARGS restart && log_success_msg || log_failure_msg
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    echo
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: ${SCRIPTNAME} {start|stop|status|restart}"
        RETVAL=2
        ;;
esac
exit $RETVAL

