#!/bin/bash
#
#   /etc/rc.d/init.d/slipstream-node
#
#   Start up the Slipstream Node Executor daemon.
#
# chkconfig: 2345 20 80
# description: Slipstream Node Executor daemon.
#
# processname: slipstream-node
# config: /etc/default/slipstream-node
# pidfile: /var/run/slipstream-node.pid

### BEGIN INIT INFO
# Provides: slipstream-node
# Required-Start: $network $local_fs
# Required-Stop: $network $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: S 0 1 6
# Short-Description: Start up the Slipstream Node Executor daemon
# Description:       Slipstream Node Executor daemon enables user
#                    application depoyment orchestration.
### END INIT INFO

# copies function named $1 to name $2
copy_function() {
    declare -F $1 > /dev/null || return 1
    eval "$(echo "${2}()"; declare -f ${1} | tail -n +2)"
}

# source function library
if [ -f /etc/rc.d/init.d/functions ]; then
    . /etc/rc.d/init.d/functions
elif [ -f /lib/lsb/init-functions ]; then
    . /lib/lsb/init-functions
    copy_function log_success_msg success
    copy_function log_failure_msg failure
fi

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NAME="slipstream-node"
if [ -d /var/lock/subsys ]; then
    LOCK_FILE=/var/lock/subsys/$NAME
else
    LOCK_FILE=/var/lock/$NAME
fi
RETVAL=0
if [ -z "$UID" ]; then
    UID=$(id -u)
fi

# default settings
DAEMON=/opt/slipstream/client/sbin/slipstream-node

if [ -f /etc/default/slipstream-node ]; then
  . /etc/default/slipstream-node
fi

DAEMON_ARGS="$DAEMON_ARGS"

start() {
    [ -x $DAEMON ] || exit 5
    [ $UID -ne 0 ] && exit 4
    echo -n "Starting ${NAME}: "
    $DAEMON $DAEMON_ARGS start && success || failure
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    echo
    return $RETVAL
}

stop() {
    [ $UID -ne 0 ] && exit 4
    echo -n "Shutting down ${NAME}: "
    $DAEMON stop && success || failure
    RETVAL=$?
    [ $RETVAL -eq 0 ] && rm -f $LOCK_FILE
    echo
    return $RETVAL
}

status() {
    [ $UID -ne 0 ] && exit 4
    $DAEMON status
    RETVAL=$?
    return $RETVAL
}

restart() {
    [ -x $DAEMON ] || exit 5
    [ $UID -ne 0 ] && exit 4
    echo -n "Re-starting ${NAME}: "
    $DAEMON $DAEMON_ARGS restart && success || failure
    RETVAL=$?
    [ $RETVAL -eq 0 ] && touch $LOCK_FILE
    echo
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: ${SCRIPTNAME} {start|stop|status|restart}"
        RETVAL=2
        ;;
esac
exit $RETVAL
